# Generated by Django 4.2.19 on 2025-02-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_temperature_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
