# Generated by Django 4.2.19 on 2025-02-23 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_measurement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 19, 27, 22, 509621)),
        ),
    ]
